const games = [
  {
    id: "game01",
    name: "FIFA 23",
    description:
      "EA SPORTS™ FIFA 23 brings The World’s Game to the pitch, with HyperMotion2 Technology that delivers even more gameplay realism, both the men’s and women’s FIFA World Cup™ coming to the game later in the the season, the addition of women’s club teams, cross-play features, and more. Experience unrivaled authenticity with over 19,000 players, 700+ teams, 100 stadiums, and over 30 leagues in FIFA 23.",
    publisher: "ELECTRONIC ARTS",
    released: "30 SEP 2022",
    poster_image: "/games/poster_fifa.jpg",
    background_image: "/games/bg_fifa.png",
    platform: "steam",
    price: "4599",
    rating: "7",
    genre: ["Multiplayer", "Simulation", "Sports"],
    requirements: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i7 6700 or AMD Ryzen 7 2700X",
      memory: "12 GB RAM",
      graphics: "NVIDIA GeForce GTX 1660 or AMD Radeon RX 5600 XT",
      storage: "100 GB available space",
    },
    popular: true,
    featured: true,
  },

  {
    id: "game02",
    name: "F1 MANAGER 2022",
    description:
      "Make your mark on Formula 1® in the officially licensed F1® Manager 2022. Choose your team and be the boss with the full 2022 roster of staff and drivers. Featuring full F1® licensing and true-to-life presentation, you won’t just play F1® Manager 2022 – you’ll live it.",
    publisher: "FRONTIER DEVELOPMENTS",
    released: "25 AUG 2022",
    poster_image: "/games/poster_f1.jpg",
    background_image: "/games/bg_f1.png",
    platform: "steam",
    price: "3569",
    rating: "8",
    genre: ["Simulation", "Singleplayer", "Sports"],
    requirements: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i5-4590 or AMD FX-8370",
      memory: "8 GB RAM",
      graphics: "NVIDIA GeForce GTX 1660 or AMD Radeon RX 5600 XT",
      storage: "30 GB available space",
    },
    popular: true,
    featured: true,
  },

  {
    id: "game03",
    name: "MARVEL'S SPIDER-MAN REMASTERED",
    description:
      "Developed by Insomniac Games in collaboration with Marvel, and optimized for PC by Nixxes Software, Marvel's Spider-Man Remastered on PC introduces an experienced Peter Parker who’s fighting big crime and iconic villains in Marvel’s New York. At the same time, he’s struggling to balance his chaotic personal life and career while the fate of Marvel’s New York rests upon his shoulders.",
    publisher: "PLAYSTATION STUDIOS",
    released: "12 AUG 2022",
    poster_image: "/games/poster_spider.jpg",
    background_image: "/games/bg_spider.png",
    platform: "steam",
    price: "4599",
    rating: "8",
    genre: ["Action", "Singleplayer"],
    requirements: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i3-4160, 3.6 GHz or AMD equivalent",
      memory: "8 GB RAM",
      graphics: "NVIDIA GTX 950 or AMD Radeon RX 470",
      storage: "75 GB available space",
    },
    popular: true,
    featured: true,
  },

  {
    id: "game04",
    name: "CYBERPUNK 2077",
    description:
      "Discover the massive open world of Night City. Every choice you make in this city affects the world around you.",
    publisher: "CD PROJEKT RED",
    released: "10 DEC 2020",
    poster_image: "/games/poster_cyber.jpg",
    background_image: "/games/bg_cyber.jpg",
    platform: "gog",
    price: "5679",
    rating: "8",
    genre: ["Action", "Singleplayer", "FPS"],
    requirements: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i5-3570K or AMD FX-8310",
      memory: "8 GB RAM",
      graphics: "NVIDIA GTX 780 or AMD Radeon RX 470",
      storage: "70 GB available space",
    },
    popular: true,
    featured: true,
  },

  {
    id: "game05",
    name: "NEED FOR SPEED 2022",
    description:
      "Developed by Insomniac Games in collaboration with Marvel, and optimized for PC by Nixxes Software, Marvel's Spider-Man Remastered on PC introduces an experienced Peter Parker who’s fighting big crime and iconic villains in Marvel’s New York. At the same time, he’s struggling to balance his chaotic personal life and career while the fate of Marvel’s New York rests upon his shoulders.",
    publisher: "ELECTRONIC ARTS",
    released: "02 DEC 2022",
    poster_image: "/games/poster_nfs.jpg",
    background_image: "/games/bg_nfs.webp",
    platform: "origin",
    price: "4829",
    rating: "7",
    genre: ["Multiplayer", "Racing", "Simulation"],
    requirements: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i3-4160, 3.6 GHz or AMD equivalent",
      memory: "8 GB RAM",
      graphics: "NVIDIA GTX 950 or AMD Radeon RX 470",
      storage: "75 GB available space",
    },
    popular: true,
    featured: true,
  },

  {
    id: "game06",
    name: "DRAGON BALL: THE BREAKERS",
    description:
      "Master each of the Raider’s powers to track and catch your victims, and evolve to get even more powerful. Cooperate with others while there is still time but the Raider or other Survivors’ decisions may force you to go it alone.",
    publisher: "BANDAI NAMCO ENTERTAINMENT",
    released: "14 OCT 2022",
    poster_image: "/games/poster_db.jpg",
    background_image: "/games/bg_db.png",
    platform: "steam",
    price: "2189",
    rating: "8",
    genre: ["Action", "Multiplayer", "Fighting"],
    requirements: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i3-7600 or AMD Ryzen 3 3100",
      memory: "8 GB RAM",
      graphics: "NVIDIA GTX 770 or AMD Radeon RX 470",
      storage: "10 GB available space",
    },
    popular: false,
    featured: true,
  },

  {
    id: "game07",
    name: "THE LORD OF THE RINGS: GOLLUM",
    description:
      "Athletic and agile, sneaky and cunning. Driven by the desire to once again hold in his hands what he lost, Gollum is one of the most fascinating characters in the world of The Lord of the Rings™.",
    publisher: "DAEDALIC ENTERTAINMENT",
    released: "31 DEC 2022",
    poster_image: "/games/poster_lotr.jpg",
    background_image: "/games/bg_lotr.png",
    platform: "epic",
    price: "2989",
    rating: "9",
    genre: ["Action", "Singleplayer"],
    requirements: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i3-4160, 3.6 GHz or AMD equivalent",
      memory: "8 GB RAM",
      graphics: "NVIDIA GTX 950 or AMD Radeon RX 470",
      storage: "100 GB available space",
    },
    popular: false,
    featured: true,
  },

  {
    id: "game08",
    name: "DEAD SPACE REMAKE",
    description:
      "The sci-fi, survival-horror classic Dead Space returns, completely rebuilt from the ground up to offer a deeper and more immersive experience.",
    publisher: "ELECTRONIC ARTS",
    released: "27 JAN 2023",
    poster_image: "/games/poster_ds.jpg",
    background_image: "/games/bg_ds.png",
    platform: "origin",
    price: "4259",
    rating: "6",
    genre: ["Action", "Horror", "Singleplayer"],
    requirements: {
      os: "Windows 10 64-bit",
      processor: "Ryzen 5 2600x or Core i5 8600",
      memory: "8 GB RAM",
      graphics: "NVIDIA GTX 950 or AMD Radeon RX 470",
      storage: "50 GB available space",
    },
    popular: false,
    featured: true,
  },

  {
    id: "game09",
    name: "HOGWARTS LEGACY",
    description:
      "Hogwarts Legacy is an immersive, open-world action RPG set in the world first introduced in the Harry Potter books. Embark on a journey through familiar and new locations as you explore and discover fantastic beasts, customize your character and craft potions, master spell casting, upgrade talents and become the wizard you want to be.",
    publisher: "WARNER BROS. INTERACTIVE",
    released: "07 FEV 2023",
    poster_image: "/games/poster_hog.jpg",
    background_image: "/games/bg_hog.png",
    platform: "epic",
    price: "5519",
    rating: "8",
    genre: ["Action", "Singleplayer"],
    requirements: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i5-8400 OR AMD Ryzen 5 2600",
      memory: "8 GB RAM",
      graphics: "NVIDIA GeForce GTX 1070 or AMD RX Vega 56",
      storage: "85 GB available space",
    },
    popular: false,
    featured: true,
  },

  {
    id: "game10",
    name: "ASSASSIN'S CREED MIRAGE",
    description:
      "Experience the story of Basim, a cunning street thief seeking answers and justice as he navigates the bustling streets of ninth–century Baghdad. Through a mysterious, ancient organization known as the Hidden Ones, he will become a deadly Master Assassin and change his fate in ways he never could have imagined.",
    publisher: "UBISOFT",
    released: "30 JUN 2023",
    poster_image: "/games/poster_assa.jpg",
    background_image: "/games/bg_assa.png",
    platform: "epic",
    price: "3449",
    rating: "8",
    genre: ["Action", "Singleplayer"],
    requirements: {
      os: "Windows 10 64-bit",
      processor: "Intel Core i3-4160, 3.6 GHz or AMD equivalent",
      memory: "8 GB RAM",
      graphics: "NVIDIA GTX 950 or AMD Radeon RX 470",
      storage: "75 GB available space",
    },
    popular: false,
    featured: true,
  },

  {
    id: "game11",
    name: "S.T.A.L.K.E.R. 2: HEART OF CHERNOBYL",
    description:
      "Chernobyl Exclusion Zone has changed dramatically after the second massive explosion in year 2006. Violent mutants, deadly anomalies, warring factions have made the Zone a very tough place to survive. Nevertheless, artifacts of unbelievable value attracted many people called S.T.A.L.K.E.R.s, who entered the Zone for their own risk striving to make a fortune out of it or even to find the Truth concealed in the Heart of Chernobyl.",
    publisher: "GSC GAME WORLD",
    released: "31 DEC 2023",
    poster_image: "/games/poster_stalker.jpg",
    background_image: "/games/bg_stalker.png",
    platform: "steam",
    price: "3679",
    rating: "7",
    genre: ["Action", "Singleplayer"],
    requirements: {
      os: "Windows 10 64-bit",
      processor: "AMD Ryzen 5 1600X / Intel Core i5-7600K",
      memory: "8 GB RAM",
      graphics: "AMD Radeon RX 580 8GB or NVIDIA GeForce GTX 1060 6GB",
      storage: "150 GB available space",
    },
    popular: false,
    featured: false,
  },

  {
    id: "game12",
    name: "FROSTPUNK 2",
    description:
      "Frostpunk 2 is the sequel to the highly acclaimed, BAFTA-nominated society survival game that blended city building, strategy and management gameplay, creating a brand new genre. Its successor takes place 30 years after the apocalyptic blizzard storm, and Earth is still overwhelmed by the icy climate of neverending frost and harsh weather.",
    publisher: "11 BIT STUDIOS",
    released: "31 DEC 2021",
    poster_image: "/games/poster_frost.jpg",
    background_image: "/games/bg_frost.png",
    platform: "origin",
    price: "3869",
    rating: "6",
    genre: ["Strategy", "Singleplayer"],
    requirements: {
      os: "Windows 10 64-bit",
      processor: "AMD Ryzen 5 1600X / Intel Core i5-7600K",
      memory: "8 GB RAM",
      graphics: "AMD Radeon RX 580 8GB or NVIDIA GeForce GTX 1060 6GB",
      storage: "60 GB available space",
    },
    popular: false,
    featured: false,
  },
];

export default games;
